### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by guyisra** [SamVerschueren/listr#131] opened 2019-03-12 17:15 UTC
this library has great potential, but lots of issues remain open and unanswered

@SamVerschueren can you add more maintainers to this?

**Comment by LitoMore** [comment] 2019-06-04 05:37
@SamVerschueren I think I can help you maintain this package.

**Comment by rap2hpoutre** [comment] 2019-07-17 12:58
@guyisra I just created a **very small** lib for my own need that has **many less feature** (for instance, it's only a _sequential_ task runner). Still, I will try to maintain it! You could have a look here: https://github.com/rap2hpoutre/taskz. Not sure it helps, I can delete my message if considered as spam (nothing to sell though).

**Comment by bunysae** [comment] 2019-10-25 07:15
@SamVerschueren
A answer about the maintenance in future would be nice.

**Comment by SamVerschueren** [comment] 2019-10-25 08:33
Hi everyone. Sorry for my absence. I was a little burned out due to personal things that happened in my life. I'm picking up open source again and planning to give Listr more attention. But I'm thinking about my mental health as well and don't want to fall in the "I owe people my time because they use my package".

@LitoMore thanks for offering your help. Does it still count? Contact me in person and we'll discuss things :).

**Comment by LitoMore** [comment] 2019-10-25 10:01
@SamVerschueren Yes. I can also help you maintain other projects.

**Comment by LitoMore** [comment] 2019-10-29 05:13
@SamVerschueren By the way, how can I get connect with you? Messenger or WhatsApp?

**Comment by SamVerschueren** [comment] 2019-10-29 06:21
Twitter DM would be the best way. We can take it up from there :ok_hand:

**Comment by LitoMore** [comment] 2019-11-03 09:48
@SamVerschueren No problem.

**Comment by vasanthdeveloper** [comment] 2020-01-05 17:49
So, the issue is still unclear? You guys haven't decided yet?

**Comment by LitoMore** [comment] 2020-01-12 12:21
@vasanthdeveloper I'm working on this issue https://github.com/SamVerschueren/listr/pull/138, but I have not idea why this CI failed.

**Comment by MarcoScabbiolo** [comment] 2020-04-16 17:25
I will try to help to maintain this package, it is great and widely used.

**Comment by vasanthdeveloper** [comment] 2020-04-16 17:28
It would be awesome if someone would rewrite the project in TypeScript with better type declarations.

**Comment by MarcoScabbiolo** [comment] 2020-04-20 18:21
Please take a look at #143 and share your thoughts

**Comment by SamVerschueren** [comment] 2020-04-29 17:37
Let's close this in favour of #143.

**Closed by SamVerschueren** 2020-04-29 17:37 UTC
